DROP TABLE IF EXISTS "category" CASCADE;
DROP TABLE IF EXISTS "country" CASCADE;
DROP TABLE IF EXISTS "movie" CASCADE;
DROP TABLE IF EXISTS "episode" CASCADE;
DROP TABLE IF EXISTS "movie_category" CASCADE;